### PR TITLE
Add primitive 'mode' option

### PR DESCRIPTION
**Pull request by aahill50**
This just adds the `mode` option from primitive

### CODE REVIEW

**Comment by dlras2** [comment]
This looks great but don't forget to update the README as well. 👍

**Comment by aahill50** [comment]
Updated the README too

**Comment by aahill50** [comment]
Anything else needed here?

**Comment by efegurkan** [comment]
@aahill50 Hey, Thank you for PR again. Nothing else is required. I think he couldn't find any free time to check and merge. :)

**Comment by aahill50** [comment]
OK thanks, just making sure 😄

**Pull request merged**
